apiVersion: v1
kind: Service
metadata:
  name: businessrule-service
  namespace: dgca-test
  labels:
    app: businessrule-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: businessrule-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: businessrule-service
  namespace: dgca-test
  labels:
    app: businessrule-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businessrule-service
  template:
    metadata:
      labels:
        app: businessrule-service
    spec:
      volumes:
        - name: destination
          secret:
            secretName: destination-service-binding-businessrule
        - name: xsuaa
          secret:
            secretName: uaa-service-binding-businessrule
      imagePullSecrets:
        - name: regcred
      containers:
        - name: businessrule-service
          image: docker.pkg.github.com/courobin/dgca-businessrule-service/dgca-businessrule-service:1.1.5-3fd867a
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dgca-businessrule-service
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 443
          volumeMounts:
            - name: destination
              mountPath: "/etc/secrets/sapcp/destination/destination-service-instance-businessrule"
              readOnly: true
            - name: xsuaa
              mountPath: "/etc/secrets/sapcp/xsuaa/uaa-service-instance-businessrule"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /rules
              port: 8080

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: uaa-service-instance-businessrule
  namespace: dgca-test
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: xsuaa-kyma-businessrule
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*/**

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: uaa-service-binding-businessrule
  namespace: dgca-test
spec:
  instanceRef:
    name: uaa-service-instance-businessrule

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: destination-service-instance-businessrule
  namespace: dgca-test
spec:
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: destination-service-binding-businessrule
  namespace: dgca-test
spec:
  instanceRef:
    name: destination-service-instance-businessrule
